language: node_js
node_js:
  - "14"
deploy:
  provider: heroku
  api_key:
    secure: K1c4t4QnjbbrrqUr9JVj0dgnQ11pRdRDxOaKgG+aguiQlz6MPMAegNKxtnE99Gz0h9MZapD/RHrUC9So1KGzSuNtDBEekrtrBdq8VdIlv1msOeoBSwTPCOp21c1UvadLi/J2+iXK4ilZJQsIqyE373HzwjnyqHKIF8IqEpHJ8Yml8nkiyz2+EgJxtNaYWo+ML6LcA+lxFvn0vdWjAD+s5zXoXVY82M+wHCjid8lgM4oO5hcACr7TKhNTFs3z/MWkdYN68UsjNLOi3VogFMJywNEgdPj6VetioYZVCj4FULfxL9/mGOypU/NSaT+oeeJL62FMn+MErCRHtcFN9ycTgUE2CQ4oQb4XTlx2cAjT5KFwHajns+hrJIVREzv2qWEptk5INo2unLk+2yD0rAEcxQDVT05idXLGXb+fx36D/oCnGQmSXXPi+TAfRns/u071wGD6weFih8yuCikqzX763GVSlsWPI6xleaegj5f45mlddsEQTEXsGwCeivFKRovZ1IcEzzAD0jDLV0Anu0ONKn36M3KliHUTZG2GSrHMYR5s98SMoEgXRShZ+iLU8HiNU2B8YwX+Bhn1RwfgRoO44+EvQuyu5wZYzS2KQstFkUKR5qUljMRUBmv8RTADOoLISjVhqMyT3KvMQw3/Jtwh7JEN8cBPp64hK9QL0BbQWfg=
  app: spleet-shorten
